name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: Build Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Get latest ninja
      uses: urkle/action-get-ninja@v1

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.22.1'

    - name: Lint
      run: ./gradlew trustdevice:lint

    - name: Test
      run: ./gradlew trustdevice:test
      
    - name: Build library
      run: ./gradlew trustdevice:assembleRelease